### ISSUE TITLE
Add tracking for rare garrison / order hall / shipyard missions

### ISSUE THREAD

**Issue by rdw-software** [SacredDuckwhale/AltMastery#1]
Only those that a) spawn very infrequently and b) award valuable goods should likely be tracked. Examples: Toys, pets, Elite Strike missions

Roadmap:

- [ ] Compile list of relevant missions, by type
- [ ] Add tracking for the GarrisonUI / mission status APIs
- [ ] Add default tasks for these missions

**Comment by SacredDuckwhale** [comment]
Order Hall:
* https://www.wowhead.com/mission=1505/a-good-dust-up
