### ISSUE TITLE
Add tracking for WOD garrison tasks

### ISSUE THREAD

**Issue by SacredDuckwhale** [SacredDuckwhale/AltMastery#12]
A few ideas:
- [ ] Garrison Cache
- [ ] Work Orders
- [ ] Herb Garden
- [ ] Mine
- [ ] Profession Quests (daily)
- [ ] Pet Battle Quests (daily)
- [ ] Fishing Quest (daily) - meh?

May need new APIs for some of these. Will look into that later, or never.
